# Generated by Django 5.2 on 2025-04-14 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_autores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frase', models.TextField()),
                ('comentarios', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_frase', models.DateField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('visible', models.BooleanField(default=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frases', to='app_autores.autor')),
            ],
            options={
                'verbose_name': 'Frase',
                'verbose_name_plural': 'Frases',
            },
        ),
    ]
