# Generated by Django 5.2 on 2025-04-16 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_autores', '0002_frase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Frase',
        ),
    ]
